linewalks/MDwalks-UI

.travis.yml

Apply Travis CI

---

package.json
src/assets/styles/font.js
src/components/__tests__/SelectedCard.test.js
src/components/card/SelectedCard.js
yarn.lock

arrow postion change to vertical center

---

src/assets/styles/font.js
src/components/__tests__/SummaryCard.test.js
src/components/card/SummaryCard.js
src/docz/Card.mdx

Create Test Code for SummaryCard

---

package.json
src/components/__tests__/Descriptions.test.js
src/components/table/Descriptions.js
src/docz/Table.mdx

Close #121 
CDM Summary 페이지 구현

Create colspan in Descriptions

---

CHANGELOG.md
index.mdx
src/components/table/Descriptions.js

Resolve Warning of React

---

.travis.yml
CHANGELOG.md
src/assets/styles/variables.js
src/components/charts/LineMergeTimeline.js
src/components/charts/SankeyChart.js
src/components/charts/Timeline.js
src/components/table/THead.js
src/helper/chartUtility.js
src/helper/chartUtility.test.js

Apply module.export to variables, charUtilty

---

CHANGELOG.md
src/components/table/Descriptions.js

fixed: Warning on Description

---

.gitignore
README.md
package.json
src/components/__tests__/SankeyChart.test.js
src/components/__tests__/__snapshots__/SankeyChart.test.js.snap
src/components/charts/SankeyChart.js
src/docz/Charts.mdx
src/helper/chartUtility.js
src/helper/chartUtility.test.js
yarn.lock

Test Code for SankeyChart with snapshot

---

CHANGELOG.md
dist/index.esm.js
dist/index.js
src/assets/styles/variables.js
src/components/charts/LineMergeTimeline.js
src/components/charts/SankeyChart.js
src/components/charts/Timeline.js
src/components/table/THead.js
src/helper/chartUtility.js
src/helper/index.js

Fix change method that request to import on chartUtiltity

---

CHANGELOG.md
dist/index.esm.js
dist/index.js
src/components/__tests__/Descriptions.test.js
src/components/table/Descriptions.js

Append property that colWidth on Descriptions

---

src/components/button/Button.js
src/docz/Button.mdx

Rename button components

---

dist/index.esm.js
dist/index.js
src/helper/index.js
src/index.js

Insert chartUtility in src/index.js

---

CHANGELOG.md
doczrc.js
src/components/__tests__/Modal.test.js
src/components/button/Button.js
src/components/layout/Heading.js
src/components/modal/Modal.js

Modify Style of Button, Modal

---

src/components/__tests__/Histogram.test.js
src/components/charts/Histogram.js

Close #193 
`yAxis`, `gridXAxis` 의 `tickValues` 를 확인하기 위해서
`const yAxis` 에 할당한 값을 다시 `this.yAxis` 에 할당했는데요
변경을 요청하시면 `this.yAxis` 에 할당하도록 변경하겠습니다.

test that checking domain, tickValues in Histogram.test.js

---

dist/index.esm.js
dist/index.js
src/components/__tests__/LineMergeTimeline.test.js
src/components/charts/LineMergeTimeline.js

closes: #184 
add scoreClickEventHandler

add scoreClickEventHandler

---

src/components/__tests__/Table.test.js
src/components/table/THead.js

Create wrapTh function in table component

---

doczrc.js
src/components/list/CheckList.js
src/components/list/CheckList.test.js
src/components/list/icn-add-sm.svg
src/docz/List.mdx
src/index.js
yarn.lock

Create CheckList Component

---

dist/index.esm.js
dist/index.js
src/components/__tests__/LineChart.test.js
src/components/charts/LineChart.js

LineChart - 요약카드 차트에 맞는 리팩토링

---

package.json
src/components/table/TBody.js
src/components/table/TFoot.js
src/components/table/THead.js
src/components/table/Table.js
src/docz/Table.mdx
yarn.lock

Reactoring table.js

---

src/components/table/TFoot.js
src/components/table/THead.js
src/components/table/Table.js

Fix: table

---

src/assets/styles/font.js
src/components/list/CheckList.js
src/components/list/CheckList.test.js

Close #216 
@jik0090 시간 될때 한 번 보세요
리뷰 신청은 아닙니다

Order checked to onChange

---

src/components/charts/LineMergeTimeline.js

MACE 위험도 차트의 선과 점 불일치

---

src/components/charts/LineChart.js

요약카드 차트 폰트 크기, 가로선 간격 수정

---

src/components/__tests__/RadarChart.test.js
src/components/charts/RadarChart.js
src/docz/Charts.mdx
src/index.js

* closes: #224 
* 레이더차트 및 테스트 추가

레이더차트 및 테스트 추가

---

index.mdx
src/components/__tests__/TreeMap.test.js
src/components/charts/TreeMap.js
src/docz/Charts.mdx
src/index.js

트리맵 차트 및 테스트 추가

---

src/assets/styles/font.js
src/components/__tests__/Tabs.test.js
src/components/button/utility.js
src/components/button/utility.test.js
src/components/layout/Tabs.js
src/docz/Layout.mdx
src/index.js

Close #240 
그려진 contents 가 다시 그려지지 않기 위해서
display: none 한게 아닌 overflow: hidden 으로 하였다

Craete Tab Component

---

src/components/button/Button.js
src/docz/Button.mdx

Create xlg Button

---

src/components/__tests__/Image.test.js
src/components/layout/Image.js

fixed: set width, height on Image Component

---

src/components/__tests__/LineChart.test.js
src/components/__tests__/RadarChart.test.js
src/components/__tests__/TreeMap.test.js
src/components/charts/Histogram.js
src/components/charts/LineChart.js
src/components/charts/LineMergeTimeline.js
src/components/charts/RadarChart.js
src/components/charts/Timeline.js
src/components/charts/TreeMap.js
src/helper/chartUtility.js
src/helper/chartUtility.test.js

차트 에러메세지 util 함수로 만들고, 모든차트에서 적용.

---

src/components/__tests__/Histogram.test.js
src/components/charts/Histogram.js
src/docz/Charts.mdx

[비교페이지] MACE 시점으로 변경되어도 툴팁에 I.I.T risk score로 고정됨

---

src/components/paper/Heatmap.js
src/docz/Charts.mdx

apply Selecbox to Heatmap

---

src/components/__tests__/Table.test.js
src/components/table/TBody.js
src/docz/Table.mdx
yarn.lock

support rowSpan to Table

---

src/components/charts/TreeMap.js

Treemap docz build 시 에러

---

index.mdx
src/components/__tests__/TimeToEvent.test.js
src/components/charts/TimeToEvent.js
src/components/charts/TimeToEvent.module.css
src/docz/Charts.mdx
src/index.js

TimeToEvent 이동 및 테스트코드 추가 

---

README.md

docs: append Commit Guide

---

README.md

fix(README): table markdown

---

index.mdx
package.json
src/assets/svg/pagination/btn_next.svg
src/assets/svg/pagination/btn_pre.svg
src/components/__tests__/Pagination.test.js
src/components/pagination/Pagination.js
src/docz/Pagenation.mdx
src/index.js
yarn.lock

* closes: #269 
Cardio레포의 Paging Component와 테스트를 UI레포로 이동
Paging 컴포넌트이름 Pagination으로 변경
Pagination 컴포넌트 docz에 추가
issue.269

 Paging 컴포넌트와 테스트를 UI레포로 이동

---

src/components/charts/LineChart.js
src/components/charts/RadarChart.js
src/helper/chartUtility.js
src/helper/chartUtility.test.js

feat(highchart): create function getTextStyle

---

.eslintrc.js
src/components/__tests__/Image.test.js
src/components/layout/Footer.js
src/components/layout/Heading.js
src/components/layout/Image.js
src/components/layout/Navbar.js
src/components/layout/Tabs.js

feat(layout): apply eslint

---

src/components/__tests__/Table.test.js
src/components/layout/Heading.js
src/components/table/TBody.js

fix(table): support undefind, null

---

src/components/list/CheckList.js
src/components/list/CheckList.test.js
src/components/list/Item.js
src/components/list/RadioList.js
src/components/list/check-box-checked-default.svg
src/components/list/check-box-unchecked-default.svg
src/components/list/icn-add-sm.svg
src/components/list/radio-button-checked-default.svg
src/components/list/radio-button-unchecked-default.svg
src/docz/List.mdx
src/index.js

checklist 와 비슷한 UX 를 가진 radiolist 생성

---

README.md

commit 가이드에 예시 색션 추가
closes: #304

feat(README): insert case of commit message

---

src/components/__tests__/ToastList.test.js
src/components/toast/Toast.js
src/components/toast/ToastCtr.js
src/components/toast/ToastList.js

improvement(Toast): apply eslint

---

src/assets/styles/form.sass

feat(form): insert className like label

---

src/components/__tests__/Pagination.test.js
src/components/pagination/Pagination.js
src/docz/Pagenation.mdx

feat(Pagination): support sm size

---

src/components/button/Button.js

fix(button): support id props

---

package.json

feat(build): build command insert version command

---

src/assets/styles/font.module.sass
src/assets/styles/font.sass
webpack.config.js
yarn.lock

feat(font): add className that fontSize, fontSize and opacity

---

webpack.config.js

fix(webpack): rollback svg file-loader

---

src/components/__tests__/THead.test.js
src/components/table/THead.js

feat(THead): support rowSpan

---

src/assets/styles/font.sass

improvement(font): append color to fs className

---

package.json
src/components/table/EmptyPlaceHolder.js
src/components/table/TBody.js
yarn.lock

feat: EmptyPlaceHolder 컴포넌트 생성

---

src/index.js

feat(EmptyPlaceHolder): insert index.js

---

src/components/button/ToggleButton.js
src/components/button/ToggleButton.test.js
src/index.js

1. data길이가 2이고, [{type, text}] 형태에 데이터를 받는다
2. selected된 항목은 click하여도 onChagne가 발생하지않는다
close:#348
closes: #348

feat: ToggleButton Component 구현

---

src/components/layout/Tabs.js

style(Tabs): remove min-width

---

src/components/table/TBody.js

1. propsTypes 추가
close#364
closes: #364

improvement: Tbody Component ESLint 적용

---

package.json
src/components/button/ButtonLink.md
src/components/card/SelectedCard.md
src/components/card/SummaryCard.md
src/components/charts/BarGauge.md
src/components/charts/LineChart.md
src/components/charts/SankeyChart.md
src/components/modal/Modal.md
webpack.config.js
yarn.lock

feat(docz): prototype react-styleguidist

---

package.json
src/components/__tests__/BarChart.test.js
src/components/__tests__/TooltipBox.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md
src/components/common/cdmCommon.js
src/components/modal/Modal.md
src/components/tooltip/TooltipBox.js
src/index.js
styleguide.config.js
webpack.config.js
yarn.lock

1. CDM BarChart를 MDwalks-UI 컴포넌트로 변경
close#369
closes: #369 

feat: CDM BarChart를 MDwalks-UI로 Migration

---

src/components/__tests__/TooltipBox.test.js
src/components/tooltip/TooltipBox.js

improvement(TooltipBox): remove showOrigin

---

src/components/charts/BarChart.js
src/components/charts/LineChart.js
src/components/common/cdmCommon.js

style(BarChart): remove BoxShadow

---

src/components/__tests__/TooltipBox.test.js
src/components/tooltip/TooltipBox.js

feat(TooltipBox): modify convert option

---

rollup.config.js
src/components/__tests__/SankeyChart.test.js
src/components/charts/SankeyChart.js
src/components/list/CheckList.js
src/components/list/RadioList.js

1. 데이터변경시 defaultNode로 초기화하는 함수 componentDidUpdate에 추가
2. list folder에서 rollup build 경고 해결
3. rollup config update
4. data 변경시state defaultNode로 변경하는 테스트 추가
closes: #401

fix(Sankey): SankeyChart 초기값문제

---

src/components/__tests__/SankeyChart.test.js
src/components/charts/LineMergeTimeline.js
src/components/charts/SankeyChart.js

1. LineMergedTimeline timeData propTypes 수정
2. Sankey defaultnNode를 defaultNode로 오타수정
closes: #410

fix: Chart 자잘한 bug 수정

---

src/components/__tests__/LineMergeTimeline.test.js
src/components/__tests__/Modal.test.js
src/components/__tests__/Pagination.test.js
src/components/__tests__/SelectedCard.test.js
src/components/__tests__/TimeToEvent.test.js
src/components/__tests__/TreeMap.test.js
src/components/button/ToggleButton.test.js
src/components/button/ToggleLargeButton.test.js
src/components/card/SelectedCard.js
src/components/charts/LineMergeTimeline.js
src/components/charts/TimeToEvent.js
src/components/charts/TimeToEvent.module.css
src/components/charts/Timeline.js
src/components/charts/TreeMap.js
src/components/list/CheckList.js
src/components/list/RadioList.js
src/components/modal/Modal.js

improvement(chart): apply eslint

---

package.json
src/components/__tests__/Descriptions.test.js
src/components/__tests__/LineChart.test.js
src/components/__tests__/Modal.test.js
src/components/__tests__/Pagination.test.js
src/components/__tests__/SelectedCard.test.js
src/components/__tests__/TFoot.test.js
src/components/__tests__/THead.test.js
src/components/__tests__/Table.test.js
src/components/button/ButtonLink.js
src/components/button/ButtonTextLink.js
src/components/form/SelectBox.js
src/components/modal/Modal.js
src/components/pagination/Pagination.js
src/components/paper/Heatmap.js
src/components/paper/Sequence.js
src/components/table/Descriptions.js
src/components/table/EmptyPlaceHolder.js
src/components/table/TBody.js
src/components/table/TFoot.js
src/components/table/THead.js
src/components/table/Table.js
src/components/table/Table.md

improvement(components): apply eslint

---

src/components/layout/Footer.js

style(footer): remove padding

---

src/assets/styles/variables.js
src/assets/styles/variables.sass
src/components/__tests__/Tabs.test.js
src/components/layout/Tabs.js
src/components/layout/Tabs.md

style(Tab): modify padding, color

---

src/components/button/TextLink.js
src/components/button/TextLink.md
src/components/button/TextLink.test.js

feat(TextLink): insert icon style

---

src/assets/styles/font.sass
src/components/button/ToggleButton.js
src/components/button/ToggleButton.md
src/components/button/ToggleLargeButton.md

feat(ToggleButton): add lg size, change color set

---

src/components/button/Button.js
src/components/button/Button.md
src/components/button/Button.test.js

style(Button): change color

---

package.json
setupTest.js
src/components/__tests__/Input.test.js
src/components/pagination/Input.js
yarn.lock

fix(Input): only number

---

src/components/button/TextLink.js

improvement(TextLink): add props that href, target, rel

---

src/components/button/TextLink.js

fix(TextLink): set hover color

---

src/assets/styles/font.sass

style(font): add fc

---

src/components/__tests__/BarChart.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md

feat(BarChart): add prop of layout(horizontal, vertical)

---

src/components/__tests__/BarChart.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md

feat(BarChart): add prop of stackId

---

src/components/table/THead.js
styleguide.config.js

fix(THead): rollback style of th

---

src/components/pagination/Pagination.js
src/components/pagination/Pagination.md

feat(Pagination): add prop of align

---

package.json
yarn.lock

chore(package): Upgrade minimist

---

src/components/layout/Tabs.js

style(Tabs): modify padding-bottom

---

src/components/table/THead.js

fix(Thead): set font-size of sort button

---

src/__tests__/index.test.js
src/components/form/RadioBox.js
src/components/form/RadioBox.md
src/components/pagination/Pagination.js
src/components/toast/Toast.md
src/index.js

feat(RadioBox): create

---

src/components/__tests__/Histogram.test.js
src/components/charts/Histogram.js
src/components/charts/Histogram.module.css
yarn.lock

1. tooltip 및 title 제거
2. 평균선에 Average Risk Score 추가
3. yMaxValue props 추가
4. Average Risk Score 포함과 yMaxValue 테스트 추가
close: #488
closes: #488 

improvement: Histogram tooltip 제거 및 평균선에 Average Risk Score 문구 추가

---

src/components/__tests__/BarChart.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md

feat(BarChart): add scroll option

---

src/components/__tests__/RadioBox.test.js
src/components/form/RadioBox.js

feat(RadioBox): add disabled of item

---

src/__tests__/index.test.js
src/components/__tests__/PieChart.test.js
src/components/charts/PieChart.js
src/components/charts/PieChart.md
src/index.js

feat(PieChart): create

---

src/components/charts/RadarChart.js
src/components/charts/RadarChart.md
src/helper/chartUtility.js
src/helper/chartUtility.test.js

1. 축, 레전드, tick, line color 변경
2. chartUtiltiy의 getTextStyleForHighcharts 속성 변경 및 테스트 변경
closes: #499
closes: #499 

improvement(RadarChart): Radar Chart의 축, 레전드와 tick, line의 color를 변경합니다.

---

src/__tests__/index.test.js
src/components/notifications/Notification.js
src/components/notifications/Notification.md
src/components/notifications/NotificationContainer.js
src/components/notifications/NotificationManager.js
src/components/notifications/Notifications.js
src/components/notifications/index.js
src/components/toast/Toast.md
src/index.js
styleguide.config.js

feat(Notifications): create

---

src/assets/styles/form.sass

style(form): remove background of select

---

package.json
src/components/notifications/Notifications.js
yarn.lock

style(Notification): add animation

---

src/components/__tests__/Table.test.js
src/components/table/Table.js

fix(table): apply columns

---

src/__tests__/index.test.js
src/components/ChartColor.js
src/components/ChartColor.md
src/components/ChartColor.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md
src/components/charts/LineChart.js
src/components/charts/LineChart.md
src/components/charts/PieChart.js
src/components/charts/PieChart.md
src/index.js

feat(ColorSet): create

---

src/components/__tests__/RadioBox.test.js
src/components/form/RadioBox.js
src/components/form/RadioBox.md

feat(RadioBox): add method of unCheckedAll

---

src/components/__tests__/BarChart.test.js
src/components/__tests__/TooltipCompareContent.test.js
src/components/charts/BarChart.js
src/components/charts/BarChart.md
src/components/common/cdmCommon.js
src/components/tooltip/TooltipCompareContent.js

feat(BarChart): multi Theme

---

src/components/form/RadioBox.js

fix(RadioBox): show Icon Image

---

src/components/__tests__/BarChart.test.js
src/components/__tests__/Table.test.js
src/components/charts/BarChart.js
src/components/common/cdmCommon.js
src/components/table/Table.js

feat(WrapperScrollBars): create

---

.eslintrc.js
src/__tests__/index.test.js
src/components/__tests__/BarChartMulti.test.js
src/components/charts/BarChartMulti.js
src/components/charts/BarChartMulti.md
src/index.js

feat(BarChartMulti): create

---

src/__tests__/index.test.js
src/index.js

feat(index): add version

---

src/components/charts/BarChart.js

improvement(BarChart): add theme

---

src/components/charts/BarChart.js
src/components/charts/cartesian/XAxis.js
src/components/charts/cartesian/YAxis.js

feat(cartesian): create XAxis, YAxis

---

src/components/charts/BarChart.js
src/components/charts/BarChartMulti.js
src/helper/chartUtility.js
src/helper/chartUtility.test.js

style(BarChartMulti): modify color, spacing

---

src/components/__tests__/SummaryCard.test.js

test(SummaryCard): apply hover style when has Event

---

src/assets/styles/font.js
src/assets/styles/font.md
src/assets/styles/font.test.js
src/components/__tests__/SummaryCard.test.js
styleguide.config.js

style(font): add TextOverflowMulti

---

src/components/__tests__/TFoot.test.js
src/components/table/TFoot.js
src/components/table/Table.md

feat(TFoot): support colSpan

---

src/components/__tests__/BarChart.test.js
src/components/__tests__/LineChart.test.js
src/components/charts/BarChart.js
src/components/charts/LineChart.js

feat(BarChart): support unit of XAxis, YAxis

---

package.json

feat(package): add script of clear:branch

---

src/components/__tests__/Axis.test.js
src/components/charts/cartesian/YAxis.js

fix(YAxis): set fontSize

---

src/helper/chartUtility.js
src/helper/chartUtility.test.js

feat(BarChart): modify barsize

---

src/components/charts/LineMergeTimeline.js

fix: LineMergedTimeline에서 MACE 용어 제거

---

src/components/__tests__/BarChart.test.js
src/components/__tests__/LineChart.test.js
src/components/charts/BarChart.js
src/components/charts/BarChartMulti.js
src/components/charts/LineChart.js
src/components/charts/LineChart.md
src/components/charts/cartesian/CartesianGrid.js
src/components/charts/cartesian/XAxis.js
src/components/charts/cartesian/YAxis.js

feat: create CartesianGrid, apply XAixs to LineChart

---

src/components/table/TFoot.js
src/components/table/Table.js

fix: set propTypes for TFoot

---

src/components/__tests__/BarChart.test.js
src/components/__tests__/BarChartMulti.test.js
src/components/__tests__/LineChart.test.js
src/components/__tests__/TooltipBox.test.js
src/components/charts/BarChart.js
src/components/charts/BarChartMulti.js
src/components/charts/LineChart.js
src/components/charts/PieChart.js
src/components/common/cdmCommon.js
src/components/tooltip/TooltipBox.js
src/components/tooltip/TooltipCompareContent.js

feat: set textMap for Charts

---

package.json
src/components/__tests__/BarChart.test.js
src/components/__tests__/BarChartMulti.test.js
src/components/__tests__/LineChart.test.js
src/components/__tests__/PieChart.test.js
src/components/__tests__/utils.js

refactor: create utils for chart test

---

src/components/ChartColor.js
src/components/ChartColor.test.js

feat(ChartColor): create ThemeBubble

---

migration.md
src/__tests__/index.test.js
src/components/__tests__/RadarChart.test.js
src/components/__tests__/RadarChartOld.test.js
src/components/__tests__/utils.js
src/components/charts/RadarChart.js
src/components/charts/RadarChart.md
src/components/charts/RadarChartOld.js
src/components/charts/RadarChartOld.md
src/components/charts/cartesian/PolarAngleAxis.js
src/index.js

feat(RadarChart): change to rechart

---

src/components/__tests__/Tabs.test.js
src/components/layout/Tabs.js
src/components/layout/Tabs.md

feat(Tabs): add type of title

---

src/components/__tests__/BarChartMulti.test.js
src/components/__tests__/commonTag.test.js
src/components/charts/BarChart.js
src/components/charts/BarChartMulti.js
src/components/charts/PieChart.md
src/components/common/commonTag.js

style: barSize, Dot margin in LegendList

---

migration.md
src/__tests__/index.test.js
src/components/TimeToEvent.test.js
src/components/__tests__/TimeToEventOld.test.js
src/components/__tests__/utils.js
src/components/charts/TimeToEvent.js
src/components/charts/TimeToEvent.md
src/components/charts/TimeToEventOld.js
src/components/charts/TimeToEventOld.md
src/components/tooltip/TooltipBox.js
src/index.js

feat(TimeToEvent): use Rechart

---

src/components/ChartColor.js

feat(ChartColor): add case to ThemeComparePrimarySea

---

src/components/ChartColor.js
src/components/ChartColor.test.js

imporvement(ChartColor): update getColorsByTheme

---

src/components/__tests__/commonTag.test.js
src/components/charts/BarChart.js
src/components/charts/BarChartMulti.js
src/components/charts/LineChart.js
src/components/charts/PieChart.js
src/components/charts/RadarChart.js
src/components/charts/TimeToEvent.js
src/components/common/commonTag.js

feat(LegendList): add hide option

---

src/components/__tests__/Item.test.js
src/components/list/CheckList.js
src/components/list/CheckList.test.js
src/components/list/Item.js
src/components/list/RadioList.js

feat(CheckList): add layout

---

src/components/__tests__/Item.test.js
src/components/charts/BarChart.js
src/components/charts/PieChart.js
src/components/list/CheckList.js
src/components/list/CheckList.test.js
src/components/list/Item.js
src/helper/ChartConfig.js
src/helper/chartUtility.js
src/helper/chartUtility.test.js

improvement: create Layout for chart

---

src/components/__tests__/Tabs.test.js
src/components/layout/Tabs.js

fix: TabUnderLine when type is TITLE

---

src/components/ChartColor.js

style: modify gold500 to sea500 in ThemeComparePrimarySea

---

src/components/charts/LineChart.js
src/components/charts/LineChart.md

1. LineChart에서 height, tick등 props를 받을수 있도록 변경
2. LineChart 문서 추가
closes: #641
closes: #XXXX

feat(LineChart): 성능차트를 위한 LineChart props 추가

---

src/components/common/commonTag.js

1. commonTag.BoxShadowInner의 box-shadow 변경
closes: #643
closes: #XXXX

improvement(commonTag): commonTag의 box-shadow 변경

---

src/components/button/Button.js

fix: Button의 proptypes 오타 수정

---

src/components/charts/LineMergeTimeline.js
src/components/charts/LineMergeTimeline.module.css

1. ChartColor를 이용하여 LineMergeTimeline 차트에 컬러셋 적용
closes: #602
closes: #602 

improvement(LineMergeTimeline): Timeline에 Color set 적용

---

src/assets/styles/tableProperties.js
src/assets/styles/variables.js
src/components/table/TBody.js
src/components/table/TFoot.js
src/components/table/THead.js
src/components/table/Table.js
src/components/table/Table.md

improvement: Table의 color 및 셀 style 변경

---

src/assets/styles/tableProperties.js
src/components/table/THead.js
src/components/table/Table.md

fix: subHeader와 tbody td의 padding 불일치 문제 수정

---

src/components/table/Table.js
src/components/table/Table.md

fix: border-bottom 미적용 버그 픽스

---

src/components/charts/LineChart.js
src/components/charts/LineChart.md

1. 기본 height 변경 및 라벨이 있을 떄, 기본 height 변경
2. 라벨 간격 조정
3. line의 width 조정
4. dot의 radius 조정
5. dot hover시 스타일 추가
6. 지시선 스타일 변경
closes: #663
closes: #663

improvement(LineChart): 라인차트 스타일 가이드 적용

---

package.json
rollup.config.js
yarn.lock

1. 기존 json 플러그인 제거
2. 새로운 json 플러그인 설치
closes: #665
closes: #665 

improvement(rollup.config.js): rollup json 플러그인 변경

---

src/components/common/commonTag.js
src/components/common/commonTag.md

improvement: LegendList에 color를 테마로 입히는 방법 적용

---

src/components/charts/BarChart.js

1. 차트 높이 props 추가
2. 차트 기본 높이 변경
3. 라벨 간격 및 스타일 적용
closes: #670
closes: #670

feat: 바 차트 스타일가이드 적용

---

src/components/charts/BarChartMulti.js

1. 차트 높이 props 추가
2. 차트 기본 높이 변경
closes: #673
closes: #673 

feat: 멀티바 차트 스타일가이드 적용

---

src/components/charts/TimeToEvent.js
src/components/charts/TimeToEvent.md

1. 시안에 맞는 컬러 렌더링 순서 변경으로 reverse함수 제거
closes: #676
closes: #676 

fix(TimeToEvent): 컬러 렌더링 순서 변경

---

src/components/charts/TimeToEvent.js
src/components/charts/TimeToEvent.md

1. showTooltip props로 tooltip의 show,hide를 제어
closes: #680
closes: #680

feat(TimeToEvent): Tooltip show,hide 옵션 추가

---

src/components/form/RadioBox.js
src/components/form/RadioBox.md
src/components/form/RadioBox.test.js

feat: RadioBox가 디자인 시안과 동일하도록 수정

---

src/assets/styles/variables.js
src/components/TimeToEvent.test.js
src/components/__tests__/BarChart.test.js
src/components/__tests__/BarChartMulti.test.js
src/components/__tests__/SankeyChart.test.js
src/components/__tests__/commonTag.test.js
src/components/button/Button.js
src/components/button/ButtonLink.test.js
src/components/button/ButtonTextLink.test.js
src/components/button/TextLink.test.js
src/components/button/ToggleButton.test.js
src/components/button/ToggleLargeButton.js
src/components/button/ToggleLargeButton.test.js
src/components/charts/Histogram.js
src/components/charts/LineMergeTimeline.js
src/components/charts/RadarChartOld.js
src/components/charts/Timeline.js
src/components/charts/TreeMap.js
src/components/paper/Sequence.js
src/components/table/Descriptions.js
src/components/toast/Toast.js
src/helper/DateUtility.test.js
src/helper/chartUtility.test.js

improvement(eslint): eslint 미적용항목 적용

---

src/components/charts/RadarChart.js

1. props로 width, height, outerRadius, margin 추가
2. defaultProps 추가
closes: #691
closes: #XXXX

feat(RadarChart): 레이더차트 수정

---

src/components/charts/PieChart.js

improvement: remove colorList of PieChart

---

src/assets/styles/font.md
src/components/layout/Heading.md

1. Heading.md를 스타일가이드 문서대로 변경
2. font.md를 스타일가이드 문서대로 변경
closes: #693
closes: #XXXX

feat: 타이포그래피 문서 추가

---

styleguide.config.js

1. 각 컴포넌트별 카테고리 분류
closes: #696
closes: #696

feat:(styleguidist): styleguidist 문서 category 화

---

src/components/__tests__/Histogram.test.js
src/components/charts/Histogram.js
src/components/charts/Histogram.module.css

1. 스타일 가이드 적용
2. module.css 제거 후 styled-component 적용
3. 스타일 가이드 적용으로 인한 yMaxValue Props 제거 및 관련된 코드 및 테스트 제거
closes: #675
closes: #XXXX

feat(Histogram): 스타일 가이드 적용

---

src/components/charts/TimeToEvent.js
src/components/common/commonTag.js

1. TimeToEvent PropTypes 수정
2. commonTag.LegendList PropTypes 수정
closes: #702
closes: #702 

fix: PropTypes Warning 제거

---

src/components/charts/LineMergeTimeline.js

1. 데이터의 4번째부터 rect의 컬러셋과 동일하게 circleColorList에 컬러셋 추가
closes: #712
closes: #XXXX

feat(LineMergedTimeline): circle 컬러셋 추가

---

src/components/list/CheckList.md
src/components/list/RadioList.js
src/components/list/RadioList.md

fix(RadioList): formatter를 처리하도록 수정 및 md 케이스 추가

---

src/components/button/ButtonLink.md
src/components/button/ButtonTextLink.md
src/components/charts/BarChart.md
src/components/charts/PieChart.md
src/components/common/commonTag.md
src/components/layout/Tabs.js
src/components/layout/Tabs.md
src/components/table/Table.md

improvement: 일부 오탈자 및 md 파일 예제 추가

---

src/components/charts/BarChart.js

feat(BarChart): barSize 추가

---

src/components/modal/Modal.js
src/components/modal/Modal.md

fix: modal이 오픈 된 후 body에 스크롤이 동작하지 않아야 합니다

---

package.json
rollup.config.js
tsconfig.json
typings/declaration.d.ts
yarn.lock

1. 타입스크립트 설정 추가
2. 불필요한 패키지 제거
closes: #727

feat: 타입스크립트 설정

---

.gitignore
src/components/charts/PieChart.js

fix(PieChart): 누락된 theme 추가

---

dist/index.esm.js
dist/index.js
package.json
rollup.config.js
src/__tests__/index.test.js
src/components/form/Tooltip.js
src/components/form/Tooltip.md
src/index.js
styleguide.config.js
yarn.lock

feat(Tooltip): Tooltip 기본형 구현

---

src/components/__tests__/BarGauge.test.js
src/components/charts/BarGauge.js
src/components/charts/BarGauge.md

1. threshold props 값을 받으면 임계치 추가
2. threshold 테스트 코드 추가
closes: #739
closes: #XXXX

feat: BarGauge 임계치 선 추가

---

src/components/charts/BarGauge.js

1. 0일 때 falsy로 인식하는 값을 _.isNumber로 변경
closes: #741
closes: #741 

fix(BarGauge): BarGauge의 임계치가 0일 때, 0을 렌더

---

src/components/list/CheckList.js
src/components/list/CheckList.md
src/components/list/CheckList.test.js

feat(checklist): 개별 disabled 기능 추가

---

src/components/charts/SankeyChart.js
src/components/paper/Heatmap.js
styleguide.config.js

improvement: Unexpected unnamed function 경고 제거

---

src/components/charts/LineMergeTimeline.js

1. 오타 수정을 편하게 하기위해 label props 추가
closes: #752
closes: #752 

fix: lineMergedTimeline 오타 수정

---

src/components/table/EmptyPlaceHolder.js
src/components/table/TBody.js
src/components/table/Table.js
src/components/table/Table.md

feat(EmptyPlaceHolder): text를 받을 수 있도록 변경

---

src/components/button/Button.js
src/components/button/Button.md

1. primary_light와 basic_light 스타일 적용
closes: #756 

fix(Button): [StyleGuide] 버튼 스타일가이드 미적용 해결

---

src/assets/styles/font.sass
src/assets/styles/form.sass
src/components/form/SelectBox.js

1. 스타일 가이드에 맞도록 form style 변경
closes: #766

feat: [StyleGuide] form style 변경

---

src/assets/svg/checkbox/btn_checkbox_checked_16.svg
src/assets/svg/checkbox/btn_checkbox_checked_disabled_16.svg
src/assets/svg/checkbox/btn_checkbox_unchecked_16.svg
src/assets/svg/checkbox/btn_checkbox_unchecked_disabled_16.svg
src/components/button/Button.js
src/components/layout/Heading.js
src/components/list/CheckBox.js
src/components/list/CheckList.js
src/components/list/Item.js
src/components/list/RadioList.js

1. RadioList hover시 box-shadow 추가
2. CheckBox 와 CheckList 16x16 사이즈 및 아이콘 추가
3. Modal Title font color 변경
4. Button hover시 box-shadow 스타일 가이드에 맞춰서 변경
closes: #771 

improvement: [StyelGuide] 스타일 가이드 피드백 적용

---

src/components/__tests__/THead.test.js
src/components/table/THead.js
src/components/table/Table.js
src/components/table/Table.md
webpack.config.js

1. defaultSort 추가
2. 소트순서 컨트롤 하도록 sortOrderList 추가
closes: #770
closes: #XXXX

feat(Table): defaultSort 추가

---

package.json
src/components/card/SelectedCard.js
webpack.config.js
yarn.lock

1. 새로운 가이드에 맞춰서 디자인 변경
closes: #777

improvement(SelectedCard): [StyleGuide] SelectedCard 디자인 변경

---

src/components/table/THead.js
src/components/table/Table.js
src/components/table/Table.md

improvement(Table): sort 초기화 기능추가

---

src/components/modal/Modal.js

feature(Modal): css 수정

---

src/components/button/ToggleButton.tsx
src/index.js
styleguide.config.js

feat(ToggleButton): 타입스크립트 변환

---

src/components/form/SelectBox.tsx
src/index.js
styleguide.config.js

feat(SelectBox): 타입스크립트 변환

---

src/components/form/Tooltip.tsx
src/index.js
styleguide.config.js

feat(Tooltip): 타입스크립트 변환

---

src/components/list/Item.tsx
styleguide.config.js

1. 타입스크립트 적용
closes: #818
closes: #XXXX

feat(Item): 타입스크립트 변환

---

src/components/__tests__/LineMergeTimeline.test.js
src/components/__tests__/Timeline.test.js
src/components/charts/LineMergeTimeline.js
src/components/charts/Timeline.js

test: Timeline 테스트 보완

---

src/components/__tests__/Navbar.test.js
src/components/__tests__/Tooltip.test.js

test: Navbar, Tooltip 테스트 보완

---

src/assets/styles/variables.ts
src/index.js

feat(variables): 타입스크립트 변환

---

src/components/pagination/Input.tsx

1. Input 컴포넌트 타입스크립트 변환
closes: #835

feat(Input): 타입스크립트 변환

---

src/components/tooltip/TooltipBox.tsx
src/index.js

feat(TooltipBox): 타입스크립트 변환

---

src/components/tooltip/TooltipCompareContent.tsx

feat(TooltipCompareContent): 타입스크립트 변환

---

.eslintrc.js
src/components/button/utility.ts
src/components/modal/Modal.js
styleguide.config.js

feat(utility): 타입스크립트 변환

---

src/assets/styles/font.ts
src/index.js
styleguide.config.js

feat(font): 타입스크립트 변환

---

src/components/table/THead.tsx
src/components/table/Table.js
styleguide.config.js

feat(THead): 타입스크립트 변환

---

src/components/table/TFoot.tsx
src/components/table/Table.js
styleguide.config.js

feat(TFoot): 타입스크립트 변환

---

src/components/table/TBody.tsx
src/components/table/Table.js
styleguide.config.js

feat(TBody): 타입스크립트 변환

---

src/components/common/commonTag.tsx
src/index.js
styleguide.config.js

feat(commonTag): 타입스크립트 변환

---

src/components/ChartColor.tsx
src/components/common/commonTag.tsx
src/index.js
styleguide.config.js

feat(ChartColor): 타입스크립트 변환

---

package.json
src/helper/chartUtility.test.js
src/helper/chartUtility.ts
src/index.js
yarn.lock

feat(chartUtility): 타입스크립트 변환

---

src/components/ChartColor.tsx
src/components/charts/BarGauge.tsx
src/index.js
styleguide.config.js

feat(BarGauge): 타입스크립트 변환

---

src/components/ChartColor.tsx
src/components/charts/RadiusGauge.tsx
src/helper/chartUtility.ts
src/index.js
styleguide.config.js

feat(RadiusGauge): 타입스크립트 변환

---

src/components/form/Tooltip.md
src/components/form/Tooltip.test.js
src/components/form/Tooltip.tsx

feat(Tooltip): placement 지원

---

src/components/__tests__/SankeyChart.test.js
src/components/charts/SankeyChart.tsx
src/helper/chartUtility.ts
src/index.js
styleguide.config.js

feat(SankeyChart): 타입스크립트 변환

---

src/components/charts/cartesian/CartesianGrid.tsx
src/components/charts/cartesian/XAxis.tsx
src/components/charts/cartesian/YAxis.tsx

feat(cartesian 폴더): 타입스크립트 변환

---

COMPONENT_REQUIREMENT.md

feat: add component_requirement template

---

README.md

docs: add Status Images of travis

---

src/components/pagination/Pagination.tsx

fix(Pagination): radius 적용

---

src/components/progressbar/ProgressBar.sass

improvement: ProgressBar sass 파일 yarn version 시 임포트 문제 수정

---

CHANGELOG.md

improvement: modify changelog

---

src/components/progressbar/ProgressBar.sass
src/components/progressbar/ProgressBar.tsx

fix(ProgressBar): border-radius 수정

---

src/components/form/Input.md
src/components/form/Input.test.js
src/components/form/Input.tsx
styleguide.config.js

closes: #504
1. pagination/input 와 이름이 겹쳐서 수정이 필요 할 듯 합니다
2. style 은 제가 임의로 잡았습니다. 수정이 필요 할 듯 합니다
3. 피드백 주시면 수정하겠습니다

feat(Input): create

---

src/components/list/CheckList.tsx
src/components/list/Item.tsx
src/components/pagination/Pagination.tsx
src/components/table/TBody.tsx
src/components/table/TFoot.tsx
src/components/table/THead.tsx
src/components/table/Table.md
src/components/table/Table.tsx

Issue945.apply omitted design

---

src/components/button/Button.sass

fix: margin-right 제거

---

src/components/button/Button.tsx
src/components/table/EmptyPlaceHolder.tsx
src/components/table/TBody.tsx
src/components/table/Table.tsx

Issue959.improvement button table

---

src/components/table/EmptyPlaceHolder.tsx

fix: 불필요한 로그 제거

---

package.json
yarn.lock

dependency 내의 패키지들에서 peerDependency warning이 발생하는 패키지에 대해 버전 업을 통해 해결합니다.
closes: #976

dependency 패키지 정리 (2)

---

src/components/Toast/Toast.md
src/components/Toast/Toast.tsx
src/components/Toast/ToastProvider.tsx

fix: remove toast function dependency
toast provider 불필요한 의존성 제거

fix: remove toast function dependency

---

src/components/button/ToggleButton.md
src/components/button/ToggleButton.tsx

improvement: toggle button text and size
- sm 사이즈 추가
- change 로직 변경
- Text 허용 항목 추가

improvement: toggle button text and size
